feature: puxar dados do pet do local storage e adicionado componente de pet de forma dinâmica
ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t3-pmv-ads-2023-1-e1-proj-web-t13-g2 pull request #52
Opened 2023-06-09 00:22 UTC by Adenilson-Oliveira

2023-06-09 12:55 UTC, emsfilho commented on src/CadastroPet/scriptCadastroPet.js
> +    petDescription.showErrorMessage(
Deixa tudo em uma linha só

2023-06-09 14:11 UTC, emsfilho requested changes

2023-06-09 14:11 UTC, emsfilho commented on src/pet/pet.js
Não entendi de modo geral oq está sendo feito aqui

2023-06-09 14:11 UTC, emsfilho commented on src/home/home.html
> +            ><img src="../images/igicon.png" alt="Logo Instagram"
Coloca em uma linha só

2023-06-09 14:11 UTC, emsfilho commented on src/home/home.html
> +          window.location.href = "http://localhost:5500/src/adotar/adotar.html";
Pq um redirect assim, não é melhor colocar direto no href?

2023-06-09 14:11 UTC, emsfilho commented on src/adotar/adotar.js
Não entendi oq está sendo feito aqui de modo geral

2023-06-09 18:02 UTC, Adenilson-Oliveira commented on src/CadastroPet/scriptCadastroPet.js
> +function builPet(petsArray) {
verdade, vou corrigir

2023-06-09 18:04 UTC, Adenilson-Oliveira commented on src/pet/pet.js
apenas renomei a variável de forma correta e retirei o console.log desnecessário

2023-06-09 18:07 UTC, Adenilson-Oliveira commented on src/adotar/adotar.js
estava apenas deixando o código mais limpo

2023-06-10 23:14 UTC, emsfilho commented on src/CadastroPet/scriptCadastroPet.js
> +    petDescription.showErrorMessage(
dgdfgd

2023-06-10 23:19 UTC, emsfilho approved these changes

2023-06-10 23:19 UTC, merged